services:
  serverguard.api:
    image: mmieczkowski/serverguard-api:latest
    environment:
      - SPRING_PROFILES_ACTIVE=development
    ports:
    - "8080:8080"
    volumes:
      - ./volumes/serverguard-api-logs:/logs/
      - ./volumes/serverguard-api-secrets:/secrets/
    restart: always
    depends_on:
      - serverguard.postgres
      - serverguard.clickhouse

  serverguard.postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
    restart: always

  serverguard.clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_PASSWORD: "mysecretpassword"
      CLICKHOUSE_USER: "default"
    restart: always

  serverguard.web:
    image: mmieczkowski/serverguard-web:local
    ports:
    - "5173:80"
    restart: always