spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    # noinspection SpringBootApplicationYaml
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

rsa:
  private-key: classpath:certs/development-private.pem
  public-key: classpath:certs/development-public.pem