spring:
  application:
    name: ServerGuard
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.hibernate.format_sql: true
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  config:
    import: optional:secrets.yml
  threads:
    virtual:
      enabled: true

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

clickhouse:
  password: mysecretpassword
  username: default
  url: http://localhost:8123/default

smtp:
  host: smtp.gmail.com
  port: 587
  username: xxx
  password: xxx

logging:
  level:
    clickhouse: DEBUG

web:
  url: http://65.109.225.191