spring:
  devtools:
    add-properties: false
  config:
    import: file:/secrets/secrets.yml

web:
  url: http://serverguard.tech

rsa:
  private-key: file:/secrets/private.pem
  public-key: file:/secrets/public.pem
