spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
  devtools:
    add-properties: true
  config:
    import: optional:secrets.yml

clickhouse:
  password: mysecretpassword
  username: default
  url: http://localhost:8123/default

web:
  url: http://localhost:5173

springdoc:
  api-docs:
    enabled: true
    path: /swagger-ui.html