spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
  devtools:
    add-properties: true

clickhouse:
  password: mysecretpassword
  username: default
  url: http://localhost:8123/default
  jdbc-url: jdbc:clickhouse://localhost:8123/default

web:
  url: http://localhost:5173

springdoc:
  api-docs:
    enabled: true
    path: /swagger-ui.html

rsa:
  private-key: classpath:certs/development-private.pem
  public-key: classpath:certs/development-public.pem

smtp:
  host: smtp.zoho.eu
  port: 587
  username: serverguard@zohomail.eu
  password: XXX
