spring:
  application:
    name: ServerGuard
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.hibernate.format_sql: true
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  threads:
    virtual:
      enabled: true
  profiles:
    active: development

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

logging:
  level:
    clickhouse: DEBUG
  file:
    name: /logs/serverguard-api.log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
      clean-history-on-start: false
      max-history: 30