name: ServerGuard Api deploy

on:
  workflow_run:
    workflows: ["ServerGuard Api build"]
    types: ["completed"]


jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
     - name: Create cert
       run: echo "${{ secrets.HETZNER_SSH_KEY }}" >> ./ssh_key

    
     - name: Create certs directory
       run: ssh -i ./ssh_key ${{ secrets.HETZNER_USER }}@${{ secrets.HETZNER_IP }} "bash -s ${{ secrets.DOCKERHUB_USERNAME }} ${{ secrets.DOCKERHUB_TOKEN }}" < ./scripts/api-deploy.sh
