name: ServerGuard Api build

on:
  push:
    branches: ["master"]
    paths: ["ServerGuard.Api/**"]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Create certs directory
        run: mkdir ./ServerGuard.Api/src/main/resources/certs

      - name: Build with Maven
        run: mvn -Dmaven.test.skip -B package --file ./ServerGuard.Api/pom.xml

      - name: Show contents of the current working directory
        run: ls -la ./ServerGuard.Api

      - name: Show contents of the target directory
        run: ls -la ./ServerGuard.Api/target

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: ./ServerGuard.Api
          push: true
          tags: mmieczkowski/serverguard-api:latest
