name: ServerGuard deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Create ssh key
        run: echo "${{ secrets.HETZNER_SSH_KEY }}" >> ./ssh_key

      - name: Set permission to ssh key
        run: chmod 400 ssh_key

      - name: Create secrets directory
        run: mkdir ./secrets

      - name: Create spring secrets file- secrets.yml
        run: echo "${{ secrets.SPRING_SECRETS }}" >> ./secrets/secrets.yml

      - name: Copy spring secrets to hetzner VM
        run: scp -o StrictHostKeyChecking=no -i ./ssh_key ./secrets/secrets.yml ${{ secrets.HETZNER_USER }}@${{ secrets.HETZNER_IP }}:/${{ secrets.HETZNER_USER }}/deploy/volumes/serverguard-api-secrets/

      - name: Create pritvate cert file - private.pem
        run: echo "${{ secrets.JWT_PRIVATE_CERT }}" >> ./secrets/private.pem

      - name: Create public cert file - public.pem
        run: echo "${{ secrets.JWT_PUBLIC_CERT }}" >> ./secrets/public.pem

      - name: Copy pritvate cert file to hetzner VM
        run: scp -o StrictHostKeyChecking=no -i ./ssh_key ./secrets/private.pem ${{ secrets.HETZNER_USER }}@${{ secrets.HETZNER_IP }}:/${{ secrets.HETZNER_USER }}/deploy/volumes/serverguard-api-secrets/

      - name: Copy public cert file to hetzner VM
        run: scp -o StrictHostKeyChecking=no -i ./ssh_key ./secrets/public.pem ${{ secrets.HETZNER_USER }}@${{ secrets.HETZNER_IP }}:/${{ secrets.HETZNER_USER }}/deploy/volumes/serverguard-api-secrets/

      - name: Copy docker compose file to hetzner VM
        run: scp -o StrictHostKeyChecking=no -i ./ssh_key ./docker-compose.yml ${{ secrets.HETZNER_USER }}@${{ secrets.HETZNER_IP }}:/${{ secrets.HETZNER_USER }}/deploy/

      - name: Deploy to Hetzner VM
        run: ssh -o StrictHostKeyChecking=no -i ./ssh_key ${{ secrets.HETZNER_USER }}@${{ secrets.HETZNER_IP }} "bash -s ${{ secrets.DOCKERHUB_USERNAME }} ${{ secrets.DOCKERHUB_TOKEN }} ${{ secrets.PG_PASSWORD }} ${{ secrets.CLICKHOUSE_PASSWORD }}" < ./scripts/deploy.sh
