name: ServerGuard Web build

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths: ["ServerGuard.Web/**"]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: ./ServerGuard.Web
          push: true
          tags: mmieczkowski/serverguard-web:latest
