version: '3.9'

services:
  serverguard.postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
    restart: always

  serverguard.clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_PASSWORD: "mysecretpassword"
      CLICKHOUSE_USER: "default"
    restart: always